apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-deployment
  labels:
    app: stress-ng-deployment
    instana-autotrace: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-ng-webserver
  template:
    metadata:
      labels:
        app: stress-ng-webserver
    spec:
      restartPolicy: Always
      containers:
      - name: stress-ng-flaskwebserver
        image: mbx1010/flask-app
        resources:
          limits:
            cpu: "200m"
            memory: "250Mi"
          requests:
            cpu: "100m"
            memory: "120Mi"
        ports:
        - containerPort: 8080

      - name: stress-ng
        image: alexeiled/stress-ng
        command: ["/stress-ng"]
        args: 
          - "-c"
          - "150"  # Number of workers
          - "-l"
          - "100"  # CPU load percentage
          - "-v"
        resources:
          limits:
            cpu: "200m"
            memory: "250Mi"
          requests:
            cpu: "100m"
            memory: "250Mi"
