# stress-ng-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-deployment
  labels: 
    name: stress-ng-deployment
    instana-autotrace: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-ng-webserver
  template:
    metadata:
      labels:
        app: stress-ng-webserver
        instana-autotrace: "true"
    spec:
      containers:
      - name: stress-ng-webserver
        image: python:3.9-slim
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m
        command: ["python", "-m", "http.server", "8080"]
      restartPolicy: Always
