# stress-ng-deployment.yaml
# home
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng-deployment
  labels: 
    name: stress-ng-deployment
    instana-autotrace: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stress-ng-webserver
  template:
    metadata:
      labels:
        app: stress-ng-webserver
    spec:
      containers:
      - name: stress-ng-flaskwebserver
        image: mbx1010/flask-app
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 0.15
            memory: 0.128
          requests:
            cpu: 0.100
      - name: stress-ng1
        args:
        - -c
        - "150"  # Last Number of worker use 150
        - -l
        - "100"  # percentage cpu Load use 100
        - -v
        command:
        - /stress-ng
        image: alexeiled/stress-ng
        name: stress-ng
        resources:
          limits:
            cpu: 0.200
          requests:
            cpu: 0.50
      restartPolicy: Always
