apiVersion: apps/v1
kind: Deployment
metadata:
  name: stress-ng1
  namespace: stress-ng1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: stress-ng1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: stress-ng1
    spec:
      containers:
      - args:
        - -c
        - "1"  # Last Number of worker use 150
        - -l
        - "1"  # percentage cpu Load use 100
        - -v
        command:
        - /stress-ng
        image: alexeiled/stress-ng
        name: stress-ng
        resources:
          limits:
            cpu: 100m
          requests:
            cpu: 50m
