apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-stress-deployment
  namespace: flaskloadgen
  labels:
    app: flask-stress-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-stress-app
  template:
    metadata:
      labels:
        app: flask-stress-app
    spec:
      containers:
      - name: flask-stress-app
        image: <your-dockerhub-username>/flask-stress-app:latest
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: flask-stress-service
  namespace: flaskloadgen
spec:
  selector:
    app: flask-stress-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
