apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-apache
  namespace: horizontal-scale
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-apache
  template:
    metadata:
      labels:
        app: php-apache
    spec:
      containers:
      - name: php-apache
        image: registry.k8s.io/hpa-example
          #        image: mbx1010/hpa-loadgen:hpa-loadgen-metrics 
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
      - name: apache-exporter
        image: lusotycoon/apache-exporter  # This is a publicly available Apache Exporter image
        ports:
        - name: exporter
          containerPort: 9117
---
apiVersion: v1
kind: Service
metadata:
  name: php-apache
  namespace: horizontal-scale
  labels:
    app: php-apache
spec:
  selector:
    app: php-apache
  type: NodePort
  ports:
  - port: 80
    name: web
    targetPort: 80
    nodePort: 31501
  - name: nodeexport
    port: 9117
    protocol: TCP
    targetPort: 9117
    nodePort: 31502






